[package]
name = "busy_beaver_rs"
version = "0.1.0"
authors = ["Adrianbakke <adrian.bakke@yahoo.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term = "*"
